# Generated by Django 6.0.2 on 2026-03-02 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to stop tracking this bill in future months'),
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.bill')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('bill', 'month', 'year')},
            },
        ),
    ]
