# Generated by Django 6.0.2 on 2026-03-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_bill_is_active_billpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='url',
            field=models.URLField(blank=True, help_text="Optional link to the bill's payment page", max_length=500),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='frequency',
            field=models.CharField(choices=[('none', 'No Repeat'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='none', help_text='How often this event repeats', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='repeat_until',
            field=models.DateField(blank=True, help_text='Last date to generate occurrences (leave blank for indefinite)', null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to stop tracking in future months'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='end_date',
            field=models.DateField(blank=True, help_text='For multi-day single events; ignored when repeating', null=True),
        ),
    ]
