# Generated by Django 6.0.2 on 2026-03-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_bill_url_calendarevent_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_variable',
            field=models.BooleanField(default=False, help_text='Amount changes each month (e.g. credit card, utilities)'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount paid; uses bill amount if blank', max_digits=10, null=True),
        ),
    ]
