# Generated by Django 6.0.2 on 2026-03-01 04:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('plate', models.CharField(blank=True, max_length=20)),
                ('odometer', models.IntegerField(blank=True, help_text='Current odometer in miles', null=True)),
                ('insurance_policy', models.CharField(blank=True, max_length=200)),
                ('title_scan', models.FileField(blank=True, null=True, upload_to='vehicle_docs/')),
                ('registration_scan', models.FileField(blank=True, null=True, upload_to='vehicle_docs/')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tires', 'Tires'), ('brakes', 'Brakes'), ('inspection', 'Inspection'), ('repair', 'Repair'), ('other', 'Other')], max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('odometer_at_service', models.IntegerField(blank=True, null=True)),
                ('next_service_odometer', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shop', models.CharField(blank=True, max_length=200)),
                ('receipt_scan', models.FileField(blank=True, null=True, upload_to='service_receipts/')),
                ('notes', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
